#!/usr/bin/env bash
# setup_repro_env.sh — reproducible venv setup for qwen_swiglu_pruning
#
# ── Usage ─────────────────────────────────────────────────────────────────────
#
#   # First-time setup (from repo root):
#   RESET_ENV=1 bash setup_repro_env.sh
#
#   # Re-run without wiping the venv (idempotent):
#   bash setup_repro_env.sh
#
#   # After setup, activate:
#   source /workspace/venvs/qwen-pruning/bin/activate
#   export PYTHONPATH=$PWD:$PYTHONPATH
#
# ── Environment variables ─────────────────────────────────────────────────────
#
#   RESET_ENV=1       Delete and recreate the venv before setup (default: 0)
#   VENV_DIR          Override venv location (default: /workspace/venvs/qwen-pruning)
#   HF_HOME           Override HuggingFace cache (default: /workspace/hf_cache)
#   SKIP_MODEL_CHECK  Set to 1 to skip the Qwen3-30B-A3B layout check (faster)
#
# ── What this does ────────────────────────────────────────────────────────────
#   1. Create (or reset) a clean Python venv
#   2. Upgrade pip / setuptools / wheel
#   3. Install torch stack from requirements-torch-cu128.txt (exact versions)
#   4. Install all other deps from requirements-locked.txt (exact versions)
#   5. Set HF_HOME and PYTHONPATH
#   6. Run scripts/check_env.py --strict
#   7. Write env_fingerprint.json (pip freeze snapshot)
#   8. Print REPRODUCIBLE ENVIRONMENT READY
# -----------------------------------------------------------------------------

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="${VENV_DIR:-/workspace/venvs/qwen-pruning}"
HF_HOME="${HF_HOME:-/workspace/hf_cache}"
RESET_ENV="${RESET_ENV:-0}"
SKIP_MODEL_CHECK="${SKIP_MODEL_CHECK:-0}"

echo ""
echo "══════════════════════════════════════════════════════════════════════"
echo "  qwen_swiglu_pruning — reproducible environment setup"
echo "══════════════════════════════════════════════════════════════════════"
echo "  Repo root : $REPO_ROOT"
echo "  Venv dir  : $VENV_DIR"
echo "  HF_HOME   : $HF_HOME"
echo "  RESET_ENV : $RESET_ENV"
echo "══════════════════════════════════════════════════════════════════════"
echo ""

# ── Step 1: Create or reset venv ─────────────────────────────────────────────
if [[ "$RESET_ENV" == "1" && -d "$VENV_DIR" ]]; then
    echo "  [1/7] RESET_ENV=1 — deleting existing venv at $VENV_DIR"
    rm -rf "$VENV_DIR"
fi

if [[ ! -d "$VENV_DIR" ]]; then
    echo "  [1/7] Creating venv at $VENV_DIR"
    mkdir -p "$(dirname "$VENV_DIR")"
    python3 -m venv "$VENV_DIR"
else
    echo "  [1/7] Venv already exists at $VENV_DIR (skipping creation)"
fi

# Activate venv
# shellcheck disable=SC1091
source "$VENV_DIR/bin/activate"
echo "        Activated: $(which python)"

# ── Step 2: Upgrade pip / setuptools / wheel ──────────────────────────────────
echo ""
echo "  [2/7] Upgrading pip / setuptools / wheel"
pip install --quiet --upgrade pip setuptools wheel

# ── Step 3: Install PyTorch stack (exact CUDA 12.8 versions) ─────────────────
echo ""
echo "  [3/7] Installing PyTorch stack (requirements-torch-cu128.txt)"
echo "         torch==2.7.1  torchvision==0.22.1  torchaudio==2.7.1  [cu128]"
pip install --quiet -r "$REPO_ROOT/requirements-torch-cu128.txt"

# Verify torch installed
python -c "import torch; print(f'        torch {torch.__version__}  CUDA {torch.version.cuda}')"

# ── Step 4: Install locked Python deps ───────────────────────────────────────
echo ""
echo "  [4/7] Installing Python deps (requirements-locked.txt)"
pip install --quiet -r "$REPO_ROOT/requirements-locked.txt"

# ── Step 5: Set environment variables ────────────────────────────────────────
echo ""
echo "  [5/7] Setting environment variables"
export HF_HOME="$HF_HOME"
export PYTHONPATH="$REPO_ROOT:${PYTHONPATH:-}"
mkdir -p "$HF_HOME"
echo "        HF_HOME   = $HF_HOME"
echo "        PYTHONPATH= $PYTHONPATH"

# Persist to activate script for future activations
ACTIVATE_EXTRAS="$VENV_DIR/bin/activate_extras.sh"
cat > "$ACTIVATE_EXTRAS" << EXTRAS
# Auto-generated by setup_repro_env.sh — source this after activating the venv
export HF_HOME="${HF_HOME}"
export PYTHONPATH="${REPO_ROOT}:\${PYTHONPATH:-}"
EXTRAS
echo "        Persistent env written to $ACTIVATE_EXTRAS"
echo "        Add to your shell: source $ACTIVATE_EXTRAS"

# ── Step 6: Run strict environment check ─────────────────────────────────────
echo ""
echo "  [6/7] Running environment check (strict mode)"
STRICT_ARGS="--strict"
if [[ "$SKIP_MODEL_CHECK" == "1" ]]; then
    STRICT_ARGS="$STRICT_ARGS --skip-model-layout"
fi
python "$REPO_ROOT/scripts/check_env.py" $STRICT_ARGS

# ── Step 7: Write env_fingerprint.json ───────────────────────────────────────
echo ""
echo "  [7/7] Writing env_fingerprint.json"
python - "$REPO_ROOT" << 'PYEOF'
import json, subprocess, sys, datetime, platform, os

repo_root = sys.argv[1]
freeze = subprocess.check_output([sys.executable, "-m", "pip", "freeze"], text=True)
pkgs = {}
for line in freeze.strip().splitlines():
    if "==" in line and not line.startswith("-"):
        name, _, ver = line.partition("==")
        pkgs[name.strip()] = ver.strip()

import torch
fingerprint = {
    "generated_at": datetime.datetime.utcnow().isoformat() + "Z",
    "python": platform.python_version(),
    "platform": platform.platform(),
    "torch": torch.__version__,
    "torch_cuda": torch.version.cuda,
    "cuda_available": torch.cuda.is_available(),
    "gpu_count": torch.cuda.device_count(),
    "gpus": [torch.cuda.get_device_name(i) for i in range(torch.cuda.device_count())] if torch.cuda.is_available() else [],
    "packages": pkgs,
    "venv": os.environ.get("VIRTUAL_ENV", ""),
}
out_path = os.path.join(repo_root, "env_fingerprint.json")
with open(out_path, "w") as f:
    json.dump(fingerprint, f, indent=2)
print(f"        {len(pkgs)} packages → {out_path}")
PYEOF

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "══════════════════════════════════════════════════════════════════════"
echo "  REPRODUCIBLE ENVIRONMENT READY"
echo "══════════════════════════════════════════════════════════════════════"
echo ""
echo "  Next steps:"
echo "    source $VENV_DIR/bin/activate"
echo "    source $VENV_DIR/bin/activate_extras.sh"
echo "    python run_experiment.py --config configs/default.yaml"
echo ""
